config/routes.rb
Tumblelog::Application.routes.draw do
  root :to => "posts#index"
  resources :posts, :only => [:index, :show]
  resources :sessions, :only => [:new, :create, :destroy]

  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'

  match "/admin/dashboard" => 'admin/dashboard#index', :as => "dashboard"
  namespace :admin do
    get "dashboard/index"
    match "/" => redirect("/admin/dashboard")

    resources :users

    match "posts/new/:post_type" => "posts#new", :as => "new_post"
    resources :posts, :except => :new
  end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer         not null, primary key
#  title        :string(255)
#  body         :text
#  created_at   :datetime
#  updated_at   :datetime
#  user_id      :integer
#  draft        :integer
#  post_type    :string(255)
#  image        :string(255)
#  quote        :string(255)
#  quote_source :string(255)
#  link         :text
#

class Post < ActiveRecord::Base
  attr_accessible :title, :body, :user_id, :draft, :post_type, :quote, :image, :quote_source, :link

  belongs_to :user

  mount_uploader :image, ImageUploader

  with_options :if => :text_post_type? do |post|
    post.validates :title, :presence => true,
              :length => { :within => 1..255 }
    post.validates :body, :presence => true
  end

  with_options :if => :image_post_type? do |post|
    post.validates :image, :presence => true
  end

  with_options :if => :quote_post_type? do |post|
    post.validates :quote, :presence => true,
              :length => { :within => 1..255 }
  end

  with_options :if => :link_post_type? do |post|
    post.validates :link, :presence => true,
      # TODO: Add support for mailto, news and ftp links.
      :format => { :with => /^(?:http(?:s)?:\/\/)?(?:www\.)?(?:[\.a-z0-9-]){1,}\.(?:[\.a-z0-9]){2,6}(?:\/(?:#?!?[\.a-z0-9_-]*\/?)*(?:\.[a-z0-9]{1,6})?(?:\?(?:[a-z0-9_]*=[:\.\/%a-z0-9_-]*&?)*)?)?$/i }
  end

  validates :user_id, :presence => true,
                      :numericality => {
                                         :only_integer => true,
                                         :greater_than_or_equal_to => 1
                                       }

  validates :draft, :presence => true

  validates :post_type, :presence => true,
                        :format => { :with => /^(text|image|quote|link|audio|video)$/ }



  def get_title
    if post_type == "text"
      title
    elsif post_type == "image"
      # TODO: Complete this
      nil
    elsif post_type == "quote"
      quote
    elsif post_type == "link"
      # TODO: Complete this
      nil
    end
  end

  def get_form_partial(post_type)
    if post_type == "text"
      "text_form"
    elsif post_type == "image"
      "image_form"
    elsif post_type == "quote"
      "quote_form"
    elsif post_type == "link"
      "link_form"
    end
  end

  private

  def text_post_type?
    post_type == "text"
  end

  def image_post_type?
    post_type == "image"
  end

  def quote_post_type?
    post_type == "quote"
  end

  def link_post_type?
    post_type == "link"
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = Post.order("created_at DESC").page(params[:page]).per(10)
    @title = "Posts"
  end

  def new
    @post = Post.new
    @form_html_options = (params[:post_type] == "image") ? { :multipart => true } : {}
    @form_partial = @post.get_form_partial(params[:post_type])
    redirect_to admin_posts_path, :alert => "You tried to create an unknown type of post..." if @form_partial.nil?
    @title = "Creating a new post..."
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      flash[:success] = "Post created successfully!"
      redirect_to admin_post_path(@post)
    else
      @title = "Creating a new post..."
      @form_partial = @post.get_form_partial(params[:post][:post_type])
      render 'new'
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
    if @post.nil?
      # FIXME: Show 404 instead
      redirect_to admin_posts_path, :alert => "Unable to find the requested post..."
    else
      @title = @post.get_title.to_s
      @show_partial = "show_#{@post.post_type}"
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
    redirect_to admin_post_path(@path), :alert => "You are not allowed to edit this post!" unless author?
    if @post.nil?
      # FIXME: Show 404 instead
      flash[:alert] = "Unable to find the requested post..."
      redirect_to admin_posts_path
    else
      @title = "Editing \"#{@post.title}\"..."
      @form_partial = @post.get_form_partial(@post.post_type)
    end
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.update_attributes(params[:post])
      flash[:success] = "Post updated successfully!"
      redirect_to admin_post_path(@post)
    else
      @title = "Editing \"#{@post.title}\"..."
      @form_partial = @post.get_form_partial(params[:post][:post_type])
      render 'edit'
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    if admin? && @post.destroy
      flash[:success] = "Post deleted successfully!"
      redirect_to admin_posts_path
    else
      redirect_to admin_posts_path, :alert => "You are not allowed to delete users!"
    end
  end

  private

  def author?
    admin? || current_user.id == @post.user_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 15).where("draft" => 0).order("created_at DESC")
  end

  def show
    @post = Post.find_by_id(params[:id])
    if @post.nil?
      # FIXME: Show 404 instead
      redirect_to root_path, :alert => "Unable to find the requested post..."
    else
      redirect_to root_url, :alert => "Unable to find the requested post!" if @post.draft == 1
      @title = @post.title if @post.post_type == "text"
      @show_partial = "show_#{@post.post_type}"
    end
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
  def get_title(post)
    if post.post_type == "text"
      post.title
    elsif post.post_type == "image"
      "(no title)"
    elsif post.post_type == "quote"
      truncate(post.quote)
    elsif post.post_type == "link"
      truncate(post.link)
    elsif post.post_type == "audio"
      "(no title)"
    elsif post.post_type == "video"
      "(no title)"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, 'error') %>
      prohibited this post from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/posts/_form.html.erb
<%= render 'error_messages' %>

<%= render @form_partial, :f => f %>

<p class="drop-down">
  <%= f.label :draft, 'Status' %>
  <%= f.select(:draft, options_for_select([["Published", 0], ["Draft", 1]], (@post.new_record? ? 0: @post.draft))) %>
</p>

<%= f.hidden_field :user_id, :value => @post.user_id || current_user.id %>
<%= f.hidden_field :post_type, :value => @post.post_type || params[:post_type] %>

<p class="button"><%= f.submit "Post", :disable_with => 'Posting...' %></p>

app/views/admin/posts/_image_form.html.erb
<p><%= f.file_field :image %></p>
<% unless @post.image_url.nil? %>
  <%= image_tag @post.image_url.to_s %>
<% end %>

app/views/admin/posts/_link_form.html.erb
<div class="field link-field">
  <p><%= f.label :link %></p>
  <p><%= f.text_field :link %></p>
</div>

app/views/admin/posts/_quote_form.html.erb
<div class="field quote-field">
  <p><%= f.label :quote, "Quote" %></p>
  <p><%= f.text_field :quote %></p>
</div>

<div class="field quote-source-field">
  <p><%= f.label :quote_source %></p>
  <p><%= f.text_field :quote_source %></p>
</div>

app/views/admin/posts/_show_image.html.erb
<p>Published on <%= format_date(@post.created_at) %> by <%= @post.user.username %></p>
<p><%= link_to "Edit", edit_admin_post_path(@post) %></p>
<%= image_tag @post.image_url(:admin).to_s %>

app/views/admin/posts/_show_link.html.erb
<p>Published on <%= format_date(@post.created_at) %> by <%= @post.user.username %></p>
<p><%= link_to "Edit", edit_admin_post_path(@post) %></p>
<p><%= link_to @post.link, @post.link %></p>

app/views/admin/posts/_show_quote.html.erb
<p>Published on <%= format_date(@post.created_at) %> by <%= @post.user.username %></p>
<p><%= link_to "Edit", edit_admin_post_path(@post) %></p>
<q cite="<%= @post.quote_source %>"><%= "&laquo;#{@post.quote}&raquo;".html_safe %></q>
<p class="quote-source"><%= @post.quote_source %></p>

app/views/admin/posts/_show_text.html.erb
<h1><%= @title %></h1>
<p><%= link_to "Edit", edit_admin_post_path(@post) %></p>
<%= @post.body.html_safe %>

app/views/admin/posts/_text_form.html.erb
<div class="field">
  <p><%= f.label :title, "Title" %></p>
  <p><%= f.text_field :title %></p>
</div>

<div class="field">
  <p><%= f.label :body, "Body" %></p>
  <p><%= f.text_area :body, :size => "20x40" %></p>
</div>

app/views/admin/posts/edit.html.erb
<h1><%= @title %></h1>

<%= form_for @post, :url => admin_post_path(@post) do |f| %>
  <%= render 'form', :f => f %>
<% end %>

app/views/admin/posts/index.html.erb
<h1><%= @title %></h1>


<section id="new-posts" class="clearfix">
  <ul>
    <li><%= link_to "Text",  admin_new_post_path("text"),  id:  "new-text-post", title: "Text"  %></li>
    <li><%= link_to "Image", admin_new_post_path("image"), id: "new-image-post", title: "Image" %></li>
    <li><%= link_to "Quote", admin_new_post_path("quote"), id: "new-quote-post", title: "Quote" %></li>
    <li><%= link_to "Link",  admin_new_post_path("link"),  id:  "new-link-post", title: "Link"  %></li>
  </ul>
</section>

<% if @posts.any? %>
  <% @posts.each do |post| %>
    <%= render 'index_post', :post => post %>
  <% end %>
  <%= paginate @posts, left: 3, right: 3 %>
<% else %>
  <p>There are no posts yet.</p>
<% end %>

app/views/admin/posts/new.html.erb
<h1><%= @title %></h1>

<%= form_for @post, :url => admin_posts_path, :html => @form_html_options do |f| %>
  <%= render 'form', :f => f %>
<% end %>

app/views/admin/posts/show.html.erb
<section class="post <%= @post.post_type %>-post post-<%= @post.id %>">
  <%= render @show_partial %>
</section>