config/routes.rb
Tumblelog::Application.routes.draw do
  root :to => "posts#index"
  resources :posts, :only => [:index, :show]
  resources :sessions, :only => [:new, :create, :destroy]

  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'

  match "/admin/dashboard" => 'admin/dashboard#index', :as => "dashboard"
  namespace :admin do
    get "dashboard/index"
    match "/" => redirect("/admin/dashboard")

    resources :users

    match "posts/new/:post_type" => "posts#new", :as => "new_post"
    resources :posts, :except => :new
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  username        :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  auth_token      :string(255)
#  admin           :integer
#

class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation, :admin
  has_secure_password
  
  has_many :posts
  
  before_create { generate_token(:auth_token) }
  
  # Validations
  validates :username, :presence => true,
                       :uniqueness => { :case_sensitive => false },
                       :length => { :within => 3..40 },
                       :format => { :with => /^[\w_]+$/i, 
                                    :message => "should only contain letters, numbers, or underscores" }

  validates :email, :presence => true,
                    :uniqueness => { :case_sensitive => false },
                    :length => { :within => 8..255 },
                    :format => { :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i }

  validates :password, :presence => true,
                       :length => { :within => 4..255 }

  validates :admin, :presence => true

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :admin_required, :only => [:new, :create, :edit, :update]

  def index
    @title = "Users"
    @users = User.paginate(:page => params[:page], :per_page => 15).order("username ASC")
  end

  def show
    @user = User.find_by_id(params[:id])
    @title = @user.username
  end

  def new
    @title = "Adding a new user..."
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Successfully created a new user!"
      redirect_to admin_user_path(@user)
    else
      @title = "Adding a new user..."
      render 'new'
    end
  end
  
  def edit
    @user = User.find_by_id(params[:id])
    @title = "Editing #{@user.username}..."
  end
  
  def update
    @user = User.find_by_id(params[:id])
    
    # NOTE: The first two conditions make sure that a malicious user (or any other user)
    #       won't try to change his username or email
    if !params[:user].include?(:username) && !params[:user].include?(:email) && @user.update_attributes(params[:user])
      flash[:success] = "You have successfully updated your info!"
      redirect_to admin_user_path(@user)
    else
      @title = "Editing #{@user.username}..."
      render 'edit'
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, 'error') %>
      prohibited this user from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <% unless message =~ /password digest/i %>
        <li><%= message %></li>
      <% end %>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/users/_form.html.erb
<%= render 'error_messages' %>

<% if @user.new_record? %>
<div class="field">
  <p><%= f.label :username %></p>
  <p><%= f.text_field :username %></p>
</div>

<div class="field">
  <p><%= f.label :email %></p>
  <p><%= f.text_field :email %></p>
</div>
<% end %>

<div class="field">
  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>
</div>

<div class="field">
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
</div>

<p><%= f.check_box :admin %> <%= f.label :admin, 'Admin' %></p>
<p class="button"><%= f.submit "Submit" %></p>

app/views/admin/users/edit.html.erb
<h1><%= @title %></h1>

<%= form_for @user, :url => admin_user_path(@user) do |f| %>
  <%= render 'form', :f => f %>
<% end %>

app/views/admin/users/index.html.erb
<h1><%= @title %></h1>

<% if admin? %>
  <p><%= link_to "Create a new user", new_admin_user_path %>
<% end %>

<% if @users.any? %>
<table class="users" summary="List of users">
  <tr>
    <th><%# View Link %></th>
    <th>Username</th>
    <th>Email</th>
    <th>Created on</th>
    <th>Updated on</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= link_to "View", admin_user_path(user) %></td>
    <% if admin? || current_user.id == user.id %>
      <td><%= link_to user.username, edit_admin_user_path(user) %></td>
    <% else %>
      <td>user.username</td>
    <% end %>
    <td><%= user.email %></td>
    <td><%= format_date(user.created_at, "short", true) %></td>
    <td><%= format_date(user.updated_at, "short", true) %></td>
  </tr>
  <% end %>
</table>

<%= will_paginate @users %>
<% else %>
<p>There are no users yet.</p>
<% end %>

app/views/admin/users/new.html.erb
<h1><%= @title %></h1>

<%= form_for @user, :url => admin_users_path do |f| %>
  <%= render 'form', :f => f %>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.username %></h1>

<p><%= link_to "Edit", edit_admin_user_path(@user) %></p>

<ul>
    <li><strong>Username:</strong> <%= @user.username %></li>
    <li><strong>Email:</strong> <%= @user.email %></li>
    <li><strong>Created on:</strong> <%= format_date @user.created_at, "long", true %></li>
    <li><strong>Updated on:</strong> <%= format_date @user.updated_at, "long", true %></li>
</ul>