config/routes.rb
Tumblelog::Application.routes.draw do
  root :to => "posts#index"
  resources :posts, :only => [:index, :show]
  resources :sessions, :only => [:new, :create, :destroy]

  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'

  match "/admin/dashboard" => 'admin/dashboard#index', :as => "dashboard"
  namespace :admin do
    get "dashboard/index"
    match "/" => redirect("/admin/dashboard")

    resources :users

    match "posts/new/:post_type" => "posts#new", :as => "new_post"
    resources :posts, :except => :new
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
  <%# Basic Page Needs %>
  <%# ================================================== %>
  <meta charset="utf-8">
  <title><%= title %></title>

  <%# HTML Shiv for IE < 9 %>
  <%# ================================================== %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%# Skeleton Framework %>
  <%# ================================================== %>
  <%= stylesheet_link_tag "base", "skeleton", "layout" %>

  <%# My CSS %>
  <%# ================================================== %>
  <%= stylesheet_link_tag "admin/base" %>

  <%# Favicons %>
  <%# ================================================== %>
  <%#<link rel="shortcut icon" href="images/favicon.ico">%>
  <%#<link rel="apple-touch-icon" href="images/apple-touch-icon.png">%>
  <%#<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">%>
  <%#<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">%>


  <%# JS %>
  <%# ================================================== %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>
  <header class="clearfix">
    <section>
    <nav>
      <p class="left"><%= link_to "Visit your site", root_url %></p>
      <p class="right">
        <% if logged_in? %>
          Logged in as <%= link_to current_user.username, admin_user_path(current_user) %> |
          <%= link_to "Log out", logout_path %>
        <% else %>
            <%= link_to "Log in", login_path %>
        <% end %>
      </p>
    </nav>
    </section>
  </header>

  <div class="container">
    <nav class="sixteen columns">
      <ul>
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "Posts", admin_posts_path %></li>
        <li><%= link_to "Users", admin_users_path %></li>
      </ul>
    </nav>
    <section id="main-content" class="sixteen columns">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </section>
    <br class="clear" />

    <%= debug params if Rails.env.development? %>
  </div> <%# End of div#container %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

  <%# Basic Page Needs %>
  <%# ================================================== %>
  <meta charset="utf-8">
  <title><%= title %></title>

  <%# HTML Shiv for IE < 9 %>
  <%# ================================================== %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%# Skeleton Framework %>
  <%# ================================================== %>
  <%= stylesheet_link_tag "base", "skeleton", "layout" %>

  <%# My CSS %>
  <%# ================================================== %>
  <%= stylesheet_link_tag "application" %>

  <%# Favicons %>
  <%# ================================================== %>
  <%#<link rel="shortcut icon" href="images/favicon.ico">%>
  <%#<link rel="apple-touch-icon" href="images/apple-touch-icon.png">%>
  <%#<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">%>
  <%#<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">%>

  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <% if logged_in? %>
      <section id="user-bar">
        <div>
          <p class="left"><%= link_to "Dashboard", dashboard_path %></p>
          <p class="right">Logged in as <%= link_to current_user.username, admin_user_path(current_user) %> | <%= link_to "Log out", logout_path %></p>
        </div>
      </section>
    <% end %>
  </header>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>

    <%= yield %>
    <%= debug params if Rails.env.development? %>
  </div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
  <head>
    <%# Basic Page Needs %>
    <%# ================================================== %>
    <meta charset="utf-8">
    <title><%= title %></title>

    <%# HTML Shiv for IE < 9 %>
    <%# ================================================== %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%# Skeleton Framework %>
    <%# ================================================== %>
    <%= stylesheet_link_tag "base", "skeleton", "layout" %>

    <%# My CSS %>
    <%# ================================================== %>
    <%= stylesheet_link_tag "sessions/base" %>

    <%# Favicons %>
    <%# ================================================== %>
    <%#<link rel="shortcut icon" href="images/favicon.ico">%>
    <%#<link rel="apple-touch-icon" href="images/apple-touch-icon.png">%>
    <%#<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">%>
    <%#<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">%>


    <%# JS %>
    <%# ================================================== %>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <section>
      <h1>Tumblelog</h1>
      <%= yield %>
    </section>
  </body>
</html>